modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="demonslayer"
version="1.0"
displayName="DemonSlayer"
authors="Instart"
description="Mode Minecraft ayant pour thème Demon Slayer"

[[dependencies.demonslayer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
